# mkcert -cert-file=pk-broles.local+1.pem -key-file=pk-broles.local+1-key.pem pk-broles.local www.pk-broles.local
# .env - DOCKER_PREFIX=pkrol
#
# if by php serve
#docker-compose exec pkrol-app php artisan serve --port=8000 --host=0.0.0.0

# sudo chown -R $USER:$USER ./

version: "3"
services:

  #php
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: "${DOCKER_PREFIX}-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network
  #mariadb
  db:
    image: mariadb
    container_name: "${DOCKER_PREFIX}-db"
    restart: always
    ports:
      - "${DOCKER_DB_PORT:-3306}:3306"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
    volumes:
      - ./docker/dbdata:/var/lib/mysql/
    networks:
      - app-network
  #nginx
  webserver:
    image: nginx:1.19.7-alpine
    container_name: "${DOCKER_PREFIX}-server"
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "${DOCKER_HOST_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#networks
networks:
  app-network:
    driver: bridge
#volumes
volumes:
  dbdata:
    driver: local
